version: '3.8'

services:
  backend-camera:
    build: .
    container_name: backend-camera
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=SY_rabbitmq  
    volumes:
      - .:/app
    devices:
      - "/dev/video0:/dev/video0"  # Use camera on Raspberry Pi
    ports:
      - "8000:8000"
    restart: always
    networks:
      - SY_network  

networks:
  SY_network:
    external: true  # Use external network



