services:
  backend-camera:
    build: .                     # ✅ Build จาก Dockerfile ในโฟลเดอร์นี้
    container_name: backend-camera
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=SY_rabbitmq
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true             # ✅ สำคัญสำหรับใช้กล้อง
    volumes:
      - ./app:/app/app
      - ./app/saved_faces_local:/app/app/saved_faces  # 🔥 เพิ่มบรรทัดนี้
    ports:
      - "8000:8000"
    restart: always
    networks:
      - SY_network

networks:
  SY_network:
    external: true
