version: '3.8'
services:
  backend-camera:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    devices:
      - "/dev/video0:/dev/video0" # กรณีใช้กล้องบน Raspberry Pi
    restart: always
